FROM quay.io/jupyter/datascience-notebook:2024-05-27

COPY req.txt /req.txt

USER root

RUN python -m pip install --upgrade pip && pip install --no-cache-dir -r /req.txt

RUN apt update && apt install -y openjdk-17-jdk